# Generated by Django 5.1.1 on 2024-09-29 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('P', '0002_alter_audios_user_alter_image_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagepage',
            name='user',
        ),
    ]
